{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-model",
    "version": "30.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lint-model-30.1.2.jar",
          "url": "lint-model-30.1.2.jar",
          "size": 158181,
          "sha512": "fbfa6261802846c4d3cde9a3730eece5748a8e77f938c46f9a2cb524a4369305affebefec3ec707ea1ed143ca7fb29d0e44672f4560ddaddd8cf5976f7d63cc2",
          "sha256": "c935307706045df6e3a6c6dece720850c1ffe3c54730cebeb940b4e26c84e238",
          "sha1": "be09a26fc830494928c11160d445475f149921ff",
          "md5": "8d0ceed54d0089a58b4496c767d97c8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lint-model-30.1.2.jar",
          "url": "lint-model-30.1.2.jar",
          "size": 158181,
          "sha512": "fbfa6261802846c4d3cde9a3730eece5748a8e77f938c46f9a2cb524a4369305affebefec3ec707ea1ed143ca7fb29d0e44672f4560ddaddd8cf5976f7d63cc2",
          "sha256": "c935307706045df6e3a6c6dece720850c1ffe3c54730cebeb940b4e26c84e238",
          "sha1": "be09a26fc830494928c11160d445475f149921ff",
          "md5": "8d0ceed54d0089a58b4496c767d97c8b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-model-30.1.2-javadoc.jar",
          "url": "lint-model-30.1.2-javadoc.jar",
          "size": 261,
          "sha512": "56f09ea456bfe769496f6c295509e9ab1b9c44885a283a7d96cb16f0fd4e9ef494ff4b9850a9cf8692cf3958d4f4c7374ef9d5cc4e76a34b23bfc21c0d384a9a",
          "sha256": "baef089518fd163e21a4447707afff0671114fc30348f1b2e0244b6a62fc5c51",
          "sha1": "8bb03461145314a4306fb12ec8d5aa10ead35fe3",
          "md5": "6fbed534818018941a70294a3bded8af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-model-30.1.2-sources.jar",
          "url": "lint-model-30.1.2-sources.jar",
          "size": 39593,
          "sha512": "c7e84ff868c1d12256986c9557ba383b2749f28f9337c792657631fd2a0efc87dfd821eb84c381fb974540b6a11380c7fb3065cdd806b8b78b49f186c96f2d6a",
          "sha256": "1975c181d06361de83790831760f2144644980f80dbf397b5fe77bdb5f1e5aaf",
          "sha1": "376feaf0f64635b29401b0929dda9f5042e821dd",
          "md5": "c81d517049e12dceae647c08d6f1bea2"
        }
      ]
    }
  ]
}
